name: MonarcAppFO releases

on:
  push:
    branches: [ 'ci-releases' ]
    tags: [ 'v*.*', 'v*.*.*', 'v*.*.*-*' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ "16.x" ]
        php-version: [ "7.4" ]

    steps:
    - uses: actions/checkout@v2

    - name: install deps
      run: sudo apt-get update && sudo apt install -y gettext

    # PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        tools: composer:v2.3
        extensions: bcmath

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Symlink Monarc modules
      run: | 
        mkdir -p module/Monarc
        ln -s ../../vendor/monarc/core module/Monarc/Core
        ln -s ../../vendor/monarc/frontoffice module/Monarc/FrontOffice

    # javascript
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Prepare node_modules
      run: | 
        mkdir -p node_modules

    # ng_anr
    - name: Clone ng_anr
      uses: actions/checkout@v2
      with:
        repository: monarc-project/ng-anr
        path: node_modules/ng_anr

    - name: checkout latest tag
      run: |
        git fetch --tags
        git checkout "$(git describe --tags $(git rev-list --tags --max-count=1))"
      working-directory: node_modules/ng_anr

    - name: Install ng_anr
      # no package-lock.json in ng_anr
      run: | 
        npm install
      working-directory: node_modules/ng_anr

    # ng_client
    - name: Clone ng_client
      uses: actions/checkout@v2
      with:
        repository: monarc-project/ng-client
        path: node_modules/ng_client

    - name: checkout latest tag
      run: |
        git fetch --tags
        git checkout "$(git describe --tags $(git rev-list --tags --max-count=1))"
      working-directory: node_modules/ng_client

    - name: Install ng_client
      # this one has a package-lock.json
      run: | 
        npm ci
      working-directory: node_modules/ng_client

    # rest of javascript deps
    - name: Install grunt
      run: npm install -g grunt-cli

    - name: Install dependencies
      run: npm install

    # final "cleanup"
    - name: post job
      run: |
        bash -x ./scripts/link_modules_resources.sh
        bash -x ./scripts/compile_translations.sh

    # prepare release
    - name: Get repository name
      id: repository
      run: echo "::set-output name=pathref::$(echo '${{ github.repository }}' | cut -d'/' -f2)-${{ env.COMPONENT }}-$(echo '${{ github.ref_name }}' | sed 's/[^[:alnum:]\.]/_/g')"

    - name: create artifact archive
      run: |
        tar --exclude .git --exclude .github -zcf '${{ steps.repository.outputs.pathref }}.tar.gz' .

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ env.COMPONENT }}/${{ steps.repository.outputs.pathref }}.tar.gz
        fail_on_unmatched_files: true
      if: startsWith(github.ref, 'refs/tags/')
